### ISSUE TITLE
Problems using minimalistic example in Vaadin 24.1.8

### ISSUE THREAD

**Issue by norbertroamsys** [xdev-software/vaadin-maps-leaflet-flow#293]
We tried to integrate Leaflet using this smart wrapper library in Vaadin 24.1.8.
In our show case/POC we used your [Example](https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/v4.0.1/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/MinimalisticDemo.java) 1:1 in our project code as a first test.

The compile & build worked just fine.

But the result is a wrong rendering that looks like this: 
![image](https://github.com/xdev-software/vaadin-maps-leaflet-flow/assets/3448010/54e08062-d956-4770-b402-b07e746f7adc)

A second issue we noticed is that the marker images are wrongly looked up by localhost:8080/ui/marker-icon-2x.png and localhost:8080/ui/marker-shadow.png instead of using a Leaflet URL prefix.
As a result no marker is shown.

Do you have a tip or solution for your integration problems?
Can e.g our additional styling be the reason for the strange positioning/rendering of the map rects?

Thanks in advance!

**Comment by AB-xdev** [comment]
Okay had a quick look however I can't tell much without knowing the whole project/codebase.

However here are some suggestions that might help you narrow down the problems:
* Tiles are displayed incorrectly
  * Maybe a browser related problem (does this also happen in other browsers? maybe a plugin is responsible?)
  * Are there any JavaScript errors inside the browser console?
* Missing marker images
  * Those should be shipped with [the library](https://github.com/xdev-software/vaadin-maps-leaflet-flow/tree/develop/vaadin-maps-leaflet-flow/src/main/resources/META-INF/resources); So if you don't do anything special it should work like in the demo
  * "instead of using a Leaflet URL prefix" I'm not sure what this means exactly as there should be no "prefix" when you copy paste the demo 1:1
* For me the whole situation looks like some kind of dependency/build problem. Maybe you use a different leaflet version somewhere and it overlaps with the one used inside the plugin?

**Comment by norbertroamsys** [comment]
@AB-xdev : Thanks for your support!

I had a look into this issue again and to my complete surprise the code now works like a charm 👍 !
I do not change anything and the complete map/all tiles are now rendered as expected. Maybe it has been a temporary network problem when loading the tiles from OpenStreetMap.org - I have no idea so far...

The only thing that wasn't working, is the loading of the marker png images. Thanks to your feedback I was able to find a workaround: 
The images are packaged in your library - yes! But the problem is that we use the `vaadin.urlMapping` [Feature](https://vaadin.com/docs/latest/integrations/spring/configuration): Every request is remapped to /ui. So e.g. in development mode the images are requested by http://localhost:8080/**ui**/marker-shadow.png.

We had the need to do that because we bundle the application together with a SwaggerUI build-in WebApp (see [StackOverflow](https://stackoverflow.com/questions/71022726/vaadin-blocks-swagger-ui) for details).

As a workaround I copied the resources to META-INF/resources/ui and they are now loaded.

Maybe you can think about a solution that considers this optional `vaadin.urlMapping` configuration as well? Other users of your nice wrapper library may have the same issue...

Thanks again and happy to hear your thoughts!

**Comment by AB-xdev** [comment]
Well I see 2 solutions here:
1. Reconfigure your routing so that it remaps these resources to the correct path
2. Instead of using the default resource supply different paths/base64encoded resources to the Leaflet components

**Comment by AB-xdev** [comment]
Closing due to no feedback
