### ISSUE TITLE
Events when the user moves and/or zooms the map

### ISSUE THREAD

**Issue by Aklakan** [xdev-software/vaadin-maps-leaflet-flow#331]
Is there any way to register server-side event handlers, such as:

```java
map.addEventListener(EventType.moveEnd, ev -> {
  // User stopped moving the map around 
  // Get the viewport bounds and use them to query the backend for how much data there is in the viewport
});
```

**Comment by Aklakan** [comment]
Seems like the suggestions in https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues/282 are similar to what I am looking for.

**Comment by Aklakan** [comment]
So this example derived from #282 works, but there should be native support for it.

Also, my impression is that the String.format (used both in this project's code and in my example) should be avoided. Vaadin has native support for properly escaping arguments provided to `getElement().executeJS("const foo = $0; const bar = $1;", someString, someJsonObject);` which String.format doesn't do - so it might lead to issues in the long run (besides being susceptible to injection) that could be avoided.
This is just a comment for general improvement.

```java
class MyComponent {
    protected void init() {
        String moveUpdateFunction = """
                function updateBoundingBox() {
                    document.getElementById('%s').$server.updateBoundingBox(%s.getBounds());
                }
            """;
        this.setId("my-map-id");
        lmap.on("moveend", String.format(moveUpdateFunction, this.getId().orElseThrow(), map.clientComponentJsAccessor()));
    }

    @ClientCallable
    public void updateBoundingBox(JsonObject json) {
        // Received JSON looks like:
        // {
        //   "_southWest":{"lat":49.67390472450039,"lng":12.158346176147463},
        //   "_northEast":{"lat":49.67648051949675,"lng":12.165791988372803}
        // }
    }
```

**Comment by AB-xdev** [comment]
Thank you for the issue.
My thoughts on these topics:

> So this example derived from https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues/282 works, but there should be native support for it.

There are 2 problems with native support:
1. We chose to not support events in the 4.0.0 rewrite as we can't guarantee the data integrity when retrieving client side data:<br/> Leaflet behaves different from your "classic" Vaadin component as no data of the component is kept on server side.<br/>When e.g. using a Vaadin Grid you can't simply insert data using your browsers developer tools as the state is also tracked on server side.<br/>This is not the case with leaflet which might allow certain attacks.
2. The amount of available events, possible payloads and variations that would need to be implement is very high which would require a lot of work.

If anyone feels free to create a (prototype) PR or some code snippets that addresses the problems I can have a look at it.
But currently this feature is not worth the implementation costs.

> Also, my impression is that the String.format (used both in this project's code and in my example) should be avoided. ...

1. This is the code of a user and not ours.<br/>It could also look like this which requires no ``String#format``
    ```java
     lmap.on("moveend", "e => document.getElementById('" + ID + "').$server.updateBoundingBox(e.getBounds())");
    ```
2. The problem is that in the code already Vaadin params are used https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/523e4bef514b6ff2e1f642b86f88bcb7e9d56721/vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/base/LEvented.java#L31, so if the user writes ``$0`` again it writes the incorrect parameter.<br/>
If you want to use Vaadin's serialization nevertheless you also can invoke e.g. ``on`` yourself like so: 
    ```java
    map.invokeSelf(".on($0, e => document.getElementById($1).$server.updateBoundingBox(e.getBounds())", "moveend", ID);
    ```
