### ISSUE TITLE
is there a way to dynamically change the font size on zoomin/out

### ISSUE THREAD

**Issue by emaayan** [xdev-software/vaadin-maps-leaflet-flow#377]
in the leaflet itself there's a way to dynamically change the font size using the onzoomend event and extracting the css properties and change them 
i'm not sure exactly how i can do this in java side, and i'm also looing for a way to do that for icons (svg icons)  
https://stackoverflow.com/questions/47943315/dynamic-change-font-size-in-leaflet-marker-tooltip-text-on-zoom-change

**Comment by AB-xdev** [comment]
Thank you for the issue.

However this is not related to our component.
That being said, you can simply build the JavaScript in Java Code as string and then send it over like this:
```java
map.on("zoomstart", "e => do your JS stuff here");
```

<sub>Also please keep in mind that we handle issues for the component here and not support request for leaflet.</sub>

**Comment by AB-xdev** [comment]
> if there was a dog that could detail the main api usage in leaflet and show the comparison of how to do that in here that would be great

Not sure what "dog" means, but there is a demo project that also has a section that shows how events can be handled.

I also modified the README to include a dedicated usage section. Hope it help :)

**Comment by emaayan** [comment]
i'm an idiot :), i meant do*c, * my primary intent is to create a map with
lots of markers that have permanent icons and tooltips
the labels are tooltips that were modified in css, (and that caused another
issue where i need to use the CssImport and i wasn't sure what CSS override
leaflet's css)
is that the main readme, i didn't see any change?

[image: image.png]

**Comment by emaayan** [comment]
> > if there was a dog that could detail the main api usage in leaflet and show the comparison of how to do that in here that would be great
> 
> Not sure what "dog" means, but there is a demo project that also has a section that shows how events can be handled.
> 
> I also modified the README to include a dedicated usage section. Hope it help :)

another thing i wanted to ask , i'm assuming i need to refer to this leaflet as pure js ? 
i'm asking because getZoom doesn't to actually exists, but from looking around it seems that leaflet in react actually has this, so when i start asking people how do i get zoomLevel in leaflet i may need to give them more context.

**Comment by AB-xdev** [comment]
> .. i didn't see any change? [image: image.png]

https://github.com/xdev-software/vaadin-maps-leaflet-flow/commits/develop/README.md
Also there is no image -.-

---

 > i'm asking because getZoom doesn't to actually exists, but from looking around it seems that leaflet in react actually has this, so when i start asking people how do i get zoomLevel in leaflet i may need to give them more context.

Falls under https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/README.md#usage

> [!NOTE]
> **The API only supports sending instructions to the client**<br/>
> Due to data integrity retrieving client-side data (that can be modified by users) is not supported.
> * Event listeners can still be registered but this needs to be done manually.<br/>[An example is available in the demo](https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/5a008511935105ea977187112cd0053c7de33e19/vaadin-maps-leaflet-flow-demo/src/main/java/software/xdev/vaadin/maps/leaflet/flow/demo/ComplexDemo.java#L223).

Also described in:
* https://github.com/xdev-software/vaadin-maps-leaflet-flow/issues/331
* https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/develop/CHANGELOG.md#400
* https://github.com/xdev-software/vaadin-maps-leaflet-flow/blob/37fc26d3d348cfc44abe7f5e8bf94881b43a88a7/vaadin-maps-leaflet-flow/src/main/java/software/xdev/vaadin/maps/leaflet/base/LEvented.java#L20-L21

**Comment by emaayan** [comment]
Thanks , i replied via email. Maybe the image failed to attach

You might wanna beef those examples:)  , because i basically know no java
script (well that's why vaadin) it took me a while to figure out that i
need to use withzoom option to actually getZoom working.
Like a examples on how to use context parameters, and reading event
arguments.
Also took me a while to see the examples in the link were using to jquery
to get the css class of leaflet, i'm trying to do that manually in document
dom , but i can't seem to retrieve it.

**Comment by AB-xdev** [comment]
> You might wanna beef those examples:)  , because i basically know no javascript

NO I won't do that because, 
a) as written above we don't and likely never will support retrieving client side manipulable data to the server as it's clearly unsafe, violates data integrity and is not recommended. There is an extremely basic example inside the demo and that's enough.
b) I'm not a JavaScript teacher - at least here. Leaflet is written in JavaScript (as is nearly everything that runs in a browser) so you have to be at least a bit familiar with JS/HTML/CSS (as should every web developer).
Leaflet already provides some [examples](https://leafletjs.com/examples.html) and they are all written in JavaScript. You may take a look at them for additional help.
Otherwise maybe consider using [Vaadin's Map](https://vaadin.com/docs/latest/components/map) which uses nearly 0 JavaScript but note however that it doesn't use leaflet, might require a commercial license and it's has less options than leaflet.

> Also took me a while to see the examples in the link were using to jquery to get the css class of leaflet, i'm trying to do that manually in document dom , but i can't seem to retrieve it.

I'm not sure what "examples in the link" you are talking about because our examples don't use JQuery at all.

---

As this issue seems to be about learning how Leaflet works, runs out-of-scope, has nothing to do with the Vaadin component and is neither a bug or feature so I'm closing it.
